x=input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(x))
print('Só tem epaços: ', x.isspace())
print('É um número: ', x.isnumeric())
print('É alfabético: ', x.isalpha())
print('É alfanumérico: ', x.isalnum())
print('Está em maísculo: ', x.upper())
print('Está em minúsculo: ', x.islower())
print('Está capitalizada: ', x.istitle())