x=input('Digite algo: ')
print(type(x))
print(x.isalnum())
print(x.isdecimal())
print(x.islower())
print(x.isspace())
print(x.isspace())
print(x.isascii())
print(x.isdigit())
print(x.isidentifier())
print(x.isprintable())
print(x.isdigit())